import {library} from '@fortawesome/fontawesome-svg-core';
//Regular icons
import {
    faPenToSquare, 
    faFlag, 
    faBell, 
    faSquareCheck,
    faCirclePlay,
    faRectangleXmark,
    faCircleQuestion,
} from '@fortawesome/free-regular-svg-icons';
//Solid icons
import {
    faTrash, 
    faSquarePlus, 
    faBan, 
    faPlus,
    faEnvelope, 
    faEnvelopeOpen,
    faCircle,
    faArrowTurnUp,
    faUserPlus,
    faSort,
    faMagnifyingGlass,
    faLock,
    faLockOpen,
    faBoxArchive,
    faRepeat,
    faCaretDown,
} from '@fortawesome/free-solid-svg-icons';
library.add(
    faPenToSquare, 
    faTrash, 
    faEnvelope, 
    faSquarePlus, 
    faBan, 
    faFlag, 
    faBell, 
    faSquareCheck, 
    faPlus,
    faEnvelopeOpen,
    faCircle,
    faArrowTurnUp,
    faUserPlus,
    faCirclePlay,
    faRectangleXmark,
    faSort,
    faMagnifyingGlass,
    faLock,
    faLockOpen,
    faBoxArchive,
    faRepeat,
    faCaretDown,
    faCircleQuestion,
);