import {library} from '@fortawesome/fontawesome-svg-core';
//Regular icons
import {
    faBell, 
    faCirclePlay,
    faCircleQuestion,
    faFlag, 
    faPenToSquare, 
    faRectangleXmark,
    faSquareCheck,
} from '@fortawesome/free-regular-svg-icons';
//Solid icons
import {
    faAngleDown,
    faAnglesDown,
    faArrowTurnUp,
    faBan, 
    faBolt,
    faBoxArchive,
    faCaretDown,
    faCircle,
    faEnvelope, 
    faEnvelopeOpen,
    faLock,
    faLockOpen,
    faMagnifyingGlass,
    faPlus,
    faPowerOff,
    faRepeat,
    faSort,
    faSquarePlus, 
    faTrash, 
    faUserPlus,
} from '@fortawesome/free-solid-svg-icons';
library.add(
    faAngleDown,
    faAnglesDown,
    faArrowTurnUp,
    faBan, 
    faBell, 
    faBolt,
    faBoxArchive,
    faCaretDown,
    faCircle,
    faCirclePlay,
    faCircleQuestion,
    faEnvelope, 
    faEnvelopeOpen,
    faFlag, 
    faLock,
    faLockOpen,
    faMagnifyingGlass,
    faPenToSquare, 
    faPlus,
    faPowerOff,
    faRectangleXmark,
    faRepeat,
    faSquareCheck, 
    faSquarePlus, 
    faSort,
    faTrash, 
    faUserPlus,
);