import {ref} from 'vue';
import {DummyTaskList} from '../pages/home/homepageService';

export const DUMMY_TASK_LIST = <DummyTaskList>{
    id: 1,
    name: 'Task examples',
    tasks: [
        {
            task_list_id: 1,
            id: 0, 
            name: 'Take the stairs', 
            description: 'Take the stairs instead of the elevator.', 
            difficulty: 1, 
            repeatable: 'NONE',
            type: 'GENERIC',
            tasks: [],
        },
        {
            task_list_id: 1,
            id: 1,
            name: 'Weekly clean up',
            description: 'Clean your home/room, water your plants, take out the trash, etc.',
            difficulty: 3, 
            repeatable: 'NONE',
            tasks: [
                {
                    task_list_id: 1,
                    id: 2, 
                    name: 'Clean the desk', 
                    description: undefined, 
                    difficulty: 2, 
                    super_task_id: 1, 
                    repeatable: 'NONE',
                    type: 'GENERIC',
                },
                {
                    task_list_id: 1,
                    id: 3, 
                    name: 'Vacuum the living room', 
                    description: '', 
                    difficulty: 2, 
                    super_task_id: 1, 
                    repeatable: 'NONE',
                    type: 'GENERIC',
                },
            ],
            type: 'GENERIC',
        },
        {
            task_list_id: 1,
            id: 4,
            name: 'Hang out with a friend',
            description: 'Rather than staying home all day, go meet up with a friend for a lovely walk through town',
            difficulty: 4, 
            repeatable: 'NONE',
            type: 'GENERIC',
            tasks: [],
        },
        {
            task_list_id: 1,
            id: 5,
            name: 'Grocery shopping',
            description: "Shopping list is on the counter. Don't forget the bread!",
            difficulty: 4, 
            repeatable: 'NONE',
            type: 'GENERIC',
            tasks: [],
        },
    ],
};

export const taskId = ref(6);

export const DUMMY_VILLAGE = {
    id: 0,
    name: 'Big Town',
    economy: 1,
    economy_exp: 100,
    economy_exp_needed: 1000,
    labour: 2,
    labour_exp: 150,
    labour_exp_needed: 1050,
    craft: 1,
    craft_exp: 850,
    craft_exp_needed: 1000,
    art: 4,
    art_exp: 450,
    art_exp_needed: 1200,
    community: 3,
    community_exp: 800,
    community_exp_needed: 1150,
    experience: 500,
    coins: 13264,
    level: 1,
    level_exp_needed: 1000,
    active: true,
};
